const EVENTS = {
  CLIENT: {
    SEND_DELETE_ROOM: "SEND_DELETE_ROOM",
    USER_LOGGED: "USER_LOGGED",
    CREATE_ROOM: "CREATE_ROOM",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    JOIN_ROOM: "JOIN_ROOM",
  },
  SERVER: {
    NEW_ROOM: "ROOMS",
    DELETE_ROOM: "DELETE_ROOM",
    ROOM_MESSAGE: "ROOM_MESSAGE",
    JOINED_ROOMS: "JOINED_ROOMS",
  },
};

export default EVENTS;
